-- =====================================================================
-- Flyway migration sample untuk plugin {{PLUGIN_ID}}.
--
-- Penomoran versi: V<YYYYMMDDHHmmss>__<deskripsi>.sql
-- Lihat README "Flyway Migration Versioning" untuk detail.
--
-- Ganti / hapus file ini sesuai schema yang dibutuhkan plugin.
-- =====================================================================

-- Contoh placeholder. Hapus & ganti dengan schema sebenarnya.
-- CREATE TABLE {{PLUGIN_NAME}}_example (
--     id          BIGINT       NOT NULL AUTO_INCREMENT,
--     name        VARCHAR(100) NOT NULL,
--     description VARCHAR(500) NULL,
--     created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
--     PRIMARY KEY (id)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
