CREATE SEQUENCE IF NOT EXISTS global_seq
    START WITH 1
    INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS uploader_seq
    START WITH 1
    INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS report_seq
    START WITH 1
    INCREMENT BY 50;
